site_name: DanielChou的部落格
site_url: https://danielchou.github.io/blog
use_directory_urls: true
docs_dir: docs
site_dir: site
remote_branch: gh-pages  # 專案網站使用 gh-pages 分支

nav:
  - 首頁: index.md
  - 文章列表: posts/index.md
  - 分類: categories.md
  - 標籤: tags.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  icon:
    logo: material/library
  language: zh-TW
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate

plugins:
  - blog
  - tags
  - search
