site_name: DanielChou的部落格
site_url: https://danielchou.github.io/blog
use_directory_urls: true
docs_dir: docs
site_dir: site
remote_branch: gh-pages # 專案網站使用 gh-pages 分支

nav:
  - 首頁: index.md
  - 文章: blog/index.md
  # - 歸檔: archive.md
  - 分類: categories.md
  - 標籤: tags.md
  - 作者: authors.md

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  icon:
    logo: material/library
  language: zh-TW
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    # - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - navigation.indexes
    - blog.authors
    - blog.categories
    - blog.archive
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切換到暗色模式
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: 切換到亮色模式

plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: full
      post_url_format: "{slug}"
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      archive: true
      archive_name: 歸檔
      archive_date_format: YYYY-MM
      archive_url_format: "archive/{date}"
      archive_toc: true
      categories: true
      categories_name: 分類
      categories_url_format: "category/{slug}"
      categories_toc: true
      categories_allowed:
        - 技術比較
        - 技術
        - 技術A
        - 技術B
        - C比較
        - 心得
        - mkdocs
      authors: true
      authors_file: authors.md
      post_readtime: false
  - tags:
      enabled: true
      tags_file: tags.md
  - search
  - table-reader:
      csv_file: table.csv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - footnotes
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - https://unpkg.com/mermaid@10.8.0/dist/mermaid.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/danielchou

  generator: false
